name: TSWorld
version: '0.13.2'
main: hu.Pdani.TSWorld.TSWorldPlugin
authors: [Pdani001]
api-version: '1.16'
description: 'A world manager plugin, written for TheServer.wtf'
website: 'www.pdani.hu'
commands:
  tsworld:
    description: TSWorld main command
    usage: '/<command> [args]'
    aliases: [tsw,tw]
permissions:
  tsworld.use:
    default: false
    description: 'Permission to use commands'
  tsworld.tp:
    default: false
    description: 'Permission to teleport to the given world'
  tsworld.tp.others:
    default: false
    description: 'Permission to teleport other players to the given world'
  tsworld.list:
    default: false
    description: 'Permission to list the loaded worlds'
  tsworld.admin:
    default: op
    description: 'Admin permission'
    children:
      tsworld.use: true
      tsworld.tp: true
      tsworld.tp.others: true
      tsworld.list: true